name: Prevent Temporary Commits

on:
  pull_request:
    branches:
      - main

jobs:
  prevent_fixups_commits:
    name: Prevent fixup commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - name: Prevent for fixup commits
        run: |
          git fetch
          BASE_SHA=$(git merge-base origin/main HEAD)
          fixup_commits=$(git log $BASE_SHA..HEAD --oneline --grep="^fixup! ")
          if [ -z "$fixup_commits" ]; then
            echo "No fixup commits found."
          else
            echo "Fixup commits found:"
            echo "$fixup_commits"
            echo "Please rebase your branch to remove fixup commits before merging."
            exit 1
          fi
  