name: Prevent Temporary Commits

on:
  pull_request:
    branches:
      - main

jobs:
  prevent_fixups_commits:
    name: Prevent fixup commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - name: Prevent for fixup commits
        run: |
          if git log -20 --oneline --grep="^fixup! "; then
            echo "Fixup commits found. Please rebase your branch to remove them."
            exit 1
          else
            echo "No fixup commits found."
          fi
  